SELECT 
    COUNTRY_REGION AS PAYS, 
    CAST(DATE AS DATE) AS date,
    CASES AS NOMBRE_CAS, 
    CASE_TYPE AS STATUT

FROM {{source("covid19","JHU_COVID_19_TIMESERIES")}}

WHERE
    COUNTRY_REGION IS NOT NULL 
    AND DATE IS NOT NULL 
    AND CASES IS NOT NULL
    AND CASE_TYPE IS NOT NULL