SELECT 
    STATE AS ETAT, COUNTY AS DISTRICT, 
    TOTAL_POPULATION, TOTAL_MALE_POPULATION AS MALE_POPULATION,
    TOTAL_FEMALE_POPULATION AS FEMALE_POPULATION

FROM {{source("covid19", "DEMOGRAPHICS")}}

WHERE 
    STATE IS NOT NULL
    AND COUNTY IS NOT NULL
    AND TOTAL_POPULATION IS NOT NULL
    AND TOTAL_MALE_POPULATION IS NOT NULL
    AND TOTAL_FEMALE_POPULATION IS NOT NULL


